# Generated by Django 3.2.8 on 2022-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estad_minoristas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n_periodo',
            name='id',
        ),
        migrations.AlterField(
            model_name='n_periodo',
            name='periodo_id_ods',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
