# Generated by Django 3.2.8 on 2022-11-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estad_minoristas', '0002_auto_20221121_0642'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventario_producto_establecimiento',
            name='inv_prod_est',
        ),
        migrations.AddField(
            model_name='inventario_producto_establecimiento',
            name='area_tipo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AlterField(
            model_name='inventario_producto_establecimiento',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='inventario_producto_establecimiento',
            constraint=models.UniqueConstraint(fields=('prod_id', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo_id', 'tipo_cod_id'), name='inv_prod_est'),
        ),
    ]
