# Generated by Django 3.2.8 on 2022-11-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estad_minoristas', '0003_auto_20221122_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste_Seccion_Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajuste_cantidad', models.FloatField(max_length=53, null=True)),
                ('ajuste_costo', models.FloatField(null=True)),
                ('ajuste_importe', models.FloatField(null=True)),
                ('ajuste_anno_ant_cantidad', models.FloatField(max_length=53)),
                ('ajuste_anno_ant_costo', models.FloatField(null=True)),
                ('ajuste_anno_ant_importe', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ajuste_Seccion_Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajuste_cantidad', models.FloatField(max_length=53, null=True)),
                ('ajuste_costo', models.FloatField(null=True)),
                ('ajuste_importe', models.FloatField(null=True)),
                ('ajuste_anno_ant_cantidad', models.FloatField(max_length=53)),
                ('ajuste_anno_ant_costo', models.FloatField(null=True)),
                ('ajuste_anno_ant_importe', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ajuste_Seccion_Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajuste_cantidad', models.FloatField(max_length=53, null=True)),
                ('ajuste_costo', models.FloatField(null=True)),
                ('ajuste_importe', models.FloatField(null=True)),
                ('ajuste_anno_ant_cantidad', models.FloatField(max_length=53)),
                ('ajuste_anno_ant_costo', models.FloatField(null=True)),
                ('ajuste_anno_ant_importe', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Seccion_Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_cantidad', models.FloatField(null=True)),
                ('compra_costo', models.FloatField(null=True)),
                ('compra_anno_ant_cantidad', models.FloatField(null=True)),
                ('compra_anno_ant_costo', models.FloatField(null=True)),
                ('compra_costo_nacional', models.FloatField(null=True)),
                ('compra_anno_ant_costo_nacional', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Seccion_Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_cantidad', models.FloatField(null=True)),
                ('compra_costo', models.FloatField(null=True)),
                ('compra_anno_ant_cantidad', models.FloatField(null=True)),
                ('compra_anno_ant_costo', models.FloatField(null=True)),
                ('compra_costo_nacional', models.FloatField(null=True)),
                ('compra_anno_ant_costo_nacional', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Seccion_Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_cantidad', models.FloatField(null=True)),
                ('compra_costo', models.FloatField(null=True)),
                ('compra_anno_ant_cantidad', models.FloatField(null=True)),
                ('compra_anno_ant_costo', models.FloatField(null=True)),
                ('compra_costo_nacional', models.FloatField(null=True)),
                ('compra_anno_ant_costo_nacional', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Seccion_Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_cantidad', models.FloatField(null=True)),
                ('inv_costo', models.FloatField(null=True)),
                ('inv_dias_existencia', models.IntegerField(null=True)),
                ('inv_potencias_dias_existencia', models.IntegerField(null=True)),
                ('inv_inicial_cantidad', models.IntegerField(null=True)),
                ('inv_inicial_costo', models.FloatField(null=True)),
                ('inv_prom_mes_cantidad', models.IntegerField(null=True)),
                ('inv_prom_mes_costo', models.FloatField(null=True)),
                ('inv_prom_cantidad', models.FloatField(max_length=53, null=True)),
                ('inv_prom_costo', models.FloatField(null=True)),
                ('inv_semestre_dias_existencia', models.IntegerField(null=True)),
                ('inv_semestre_uso', models.FloatField(null=True)),
                ('inv_anno_ant_cantidad', models.FloatField(null=True)),
                ('inv_anno_ant_costo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Seccion_Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_cantidad', models.FloatField(null=True)),
                ('inv_costo', models.FloatField(null=True)),
                ('inv_dias_existencia', models.IntegerField(null=True)),
                ('inv_potencias_dias_existencia', models.IntegerField(null=True)),
                ('inv_inicial_cantidad', models.IntegerField(null=True)),
                ('inv_inicial_costo', models.FloatField(null=True)),
                ('inv_prom_mes_cantidad', models.IntegerField(null=True)),
                ('inv_prom_mes_costo', models.FloatField(null=True)),
                ('inv_prom_cantidad', models.FloatField(max_length=53, null=True)),
                ('inv_prom_costo', models.FloatField(null=True)),
                ('inv_semestre_dias_existencia', models.IntegerField(null=True)),
                ('inv_semestre_uso', models.FloatField(null=True)),
                ('inv_anno_ant_cantidad', models.FloatField(null=True)),
                ('inv_anno_ant_costo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Seccion_Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_cantidad', models.FloatField(null=True)),
                ('inv_costo', models.FloatField(null=True)),
                ('inv_dias_existencia', models.IntegerField(null=True)),
                ('inv_potencias_dias_existencia', models.IntegerField(null=True)),
                ('inv_inicial_cantidad', models.IntegerField(null=True)),
                ('inv_inicial_costo', models.FloatField(null=True)),
                ('inv_prom_mes_cantidad', models.IntegerField(null=True)),
                ('inv_prom_mes_costo', models.FloatField(null=True)),
                ('inv_prom_cantidad', models.FloatField(max_length=53, null=True)),
                ('inv_prom_costo', models.FloatField(null=True)),
                ('inv_semestre_dias_existencia', models.IntegerField(null=True)),
                ('inv_semestre_uso', models.FloatField(null=True)),
                ('inv_anno_ant_cantidad', models.FloatField(null=True)),
                ('inv_anno_ant_costo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia_Seccion_Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transf_cantidad', models.FloatField(max_length=53, null=True)),
                ('transf_costo', models.FloatField(null=True)),
                ('transf_anno_ant_cantidad', models.FloatField(max_length=53)),
                ('transf_anno_ant_costo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia_Seccion_Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transf_cantidad', models.FloatField(max_length=53, null=True)),
                ('transf_costo', models.FloatField(null=True)),
                ('transf_anno_ant_cantidad', models.FloatField(max_length=53)),
                ('transf_anno_ant_costo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia_Seccion_Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transf_cantidad', models.FloatField(max_length=53, null=True)),
                ('transf_costo', models.FloatField(null=True)),
                ('transf_anno_ant_cantidad', models.FloatField(max_length=53)),
                ('transf_anno_ant_costo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_Seccion_Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_cantidad', models.FloatField(null=True)),
                ('venta_costo', models.FloatField(null=True)),
                ('venta_importe', models.FloatField(null=True)),
                ('venta_prom_cantidad', models.FloatField(null=True)),
                ('venta_prom_costo', models.FloatField(null=True)),
                ('venta_prom_importe', models.FloatField(null=True)),
                ('venta_semestre_cantidad', models.FloatField(null=True)),
                ('venta_semestre_costo', models.FloatField(null=True)),
                ('venta_semestre_importe', models.FloatField(null=True)),
                ('venta_anno_ant_cantidad', models.FloatField(null=True)),
                ('venta_anno_ant_costo', models.FloatField(null=True)),
                ('venta_anno_ant_importe', models.FloatField(null=True)),
                ('venta_importe_nacional', models.FloatField(null=True)),
                ('venta_anno_ant_importe_nacional', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_Seccion_Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_cantidad', models.FloatField(null=True)),
                ('venta_costo', models.FloatField(null=True)),
                ('venta_importe', models.FloatField(null=True)),
                ('venta_prom_cantidad', models.FloatField(null=True)),
                ('venta_prom_costo', models.FloatField(null=True)),
                ('venta_prom_importe', models.FloatField(null=True)),
                ('venta_semestre_cantidad', models.FloatField(null=True)),
                ('venta_semestre_costo', models.FloatField(null=True)),
                ('venta_semestre_importe', models.FloatField(null=True)),
                ('venta_anno_ant_cantidad', models.FloatField(null=True)),
                ('venta_anno_ant_costo', models.FloatField(null=True)),
                ('venta_anno_ant_importe', models.FloatField(null=True)),
                ('venta_importe_nacional', models.FloatField(null=True)),
                ('venta_anno_ant_importe_nacional', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas_Seccion_Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_cantidad', models.FloatField(null=True)),
                ('venta_costo', models.FloatField(null=True)),
                ('venta_importe', models.FloatField(null=True)),
                ('venta_prom_cantidad', models.FloatField(null=True)),
                ('venta_prom_costo', models.FloatField(null=True)),
                ('venta_prom_importe', models.FloatField(null=True)),
                ('venta_semestre_cantidad', models.FloatField(null=True)),
                ('venta_semestre_costo', models.FloatField(null=True)),
                ('venta_semestre_importe', models.FloatField(null=True)),
                ('venta_anno_ant_cantidad', models.FloatField(null=True)),
                ('venta_anno_ant_costo', models.FloatField(null=True)),
                ('venta_anno_ant_importe', models.FloatField(null=True)),
                ('venta_importe_nacional', models.FloatField(null=True)),
                ('venta_anno_ant_importe_nacional', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ajuste_departamento_complejo',
            name='ajuste_dep_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='ajuste_departamento_establecimiento',
            name='ajuste_dep_est',
        ),
        migrations.RemoveConstraint(
            model_name='ajuste_departamento_sucursal',
            name='ajuste_dep_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='ajuste_linea_complejo',
            name='ajuste_linea_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='ajuste_linea_establecimiento',
            name='ajuste_linea_prod',
        ),
        migrations.RemoveConstraint(
            model_name='ajuste_linea_sucursal',
            name='ajuste_linea_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='compra_departamento_complejo',
            name='compra_dep_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='compra_departamento_establecimiento',
            name='compra_dep_est',
        ),
        migrations.RemoveConstraint(
            model_name='compra_departamento_sucursal',
            name='compra_dep_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='compra_linea_complejo',
            name='compra_linea_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='compra_linea_establecimiento',
            name='compra_linea_prod',
        ),
        migrations.RemoveConstraint(
            model_name='compra_linea_sucursal',
            name='compra_linea_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='inventario_departamento_complejo',
            name='inv_dep_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='inventario_departamento_establecimiento',
            name='inv_dep_est',
        ),
        migrations.RemoveConstraint(
            model_name='inventario_departamento_sucursal',
            name='inv_dep_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='inventario_linea_complejo',
            name='inv_linea_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='inventario_linea_establecimiento',
            name='inv_linea_prod',
        ),
        migrations.RemoveConstraint(
            model_name='inventario_linea_sucursal',
            name='inv_linea_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='transferencia_departamento_complejo',
            name='transf_dep_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='transferencia_departamento_establecimiento',
            name='transf_dep_est',
        ),
        migrations.RemoveConstraint(
            model_name='transferencia_departamento_sucursal',
            name='transf_dep_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='transferencia_linea_complejo',
            name='transf__linea_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='transferencia_linea_establecimiento',
            name='transf_linea_prod',
        ),
        migrations.RemoveConstraint(
            model_name='transferencia_linea_sucursal',
            name='transf_linea_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='ventas_departamento_complejo',
            name='venta_dep_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='ventas_departamento_establecimiento',
            name='venta_dep_est',
        ),
        migrations.RemoveConstraint(
            model_name='ventas_departamento_sucursal',
            name='venta_dep_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='ventas_linea_complejo',
            name='venta_linea_complejo',
        ),
        migrations.RemoveConstraint(
            model_name='ventas_linea_establecimiento',
            name='venta_linea_prod',
        ),
        migrations.RemoveConstraint(
            model_name='ventas_linea_sucursal',
            name='venta_linea_sucursal',
        ),
        migrations.RemoveField(
            model_name='ajuste_departamento_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ajuste_departamento_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ajuste_departamento_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ajuste_linea_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ajuste_linea_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ajuste_linea_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='compra_departamento_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='compra_departamento_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='compra_departamento_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='compra_linea_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='compra_linea_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='compra_linea_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='inventario_departamento_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='inventario_departamento_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='inventario_departamento_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='inventario_linea_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='inventario_linea_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='inventario_linea_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='transferencia_departamento_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='transferencia_departamento_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='transferencia_departamento_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='transferencia_linea_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='transferencia_linea_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='transferencia_linea_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ventas_departamento_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ventas_departamento_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ventas_departamento_sucursal',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ventas_linea_complejo',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ventas_linea_establecimiento',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='ventas_linea_sucursal',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='ajuste_departamento_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ajuste_departamento_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ajuste_departamento_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ajuste_linea_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ajuste_linea_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ajuste_linea_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_departamento_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_departamento_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_departamento_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_linea_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_linea_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_linea_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_departamento_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_departamento_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_departamento_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_linea_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_linea_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_linea_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_departamento_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_departamento_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_departamento_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_linea_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_linea_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_linea_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_departamento_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_departamento_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_departamento_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_linea_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_linea_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_linea_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_departamento_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_dep_complejo'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_departamento_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_dep_est'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_departamento_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_dep_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_linea_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_linea_complejo'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_linea_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_linea_prod'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_linea_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_linea_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='compra_departamento_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_dep_complejo'),
        ),
        migrations.AddConstraint(
            model_name='compra_departamento_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_dep_est'),
        ),
        migrations.AddConstraint(
            model_name='compra_departamento_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_dep_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='compra_linea_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_linea_complejo'),
        ),
        migrations.AddConstraint(
            model_name='compra_linea_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_linea_prod'),
        ),
        migrations.AddConstraint(
            model_name='compra_linea_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_linea_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='inventario_departamento_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_dep_complejo'),
        ),
        migrations.AddConstraint(
            model_name='inventario_departamento_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_dep_est'),
        ),
        migrations.AddConstraint(
            model_name='inventario_departamento_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_dep_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='inventario_linea_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_linea_complejo'),
        ),
        migrations.AddConstraint(
            model_name='inventario_linea_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_linea_prod'),
        ),
        migrations.AddConstraint(
            model_name='inventario_linea_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_linea_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_departamento_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf_dep_complejo'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_departamento_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf_dep_est'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_departamento_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf_dep_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_linea_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf__linea_complejo'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_linea_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf_linea_prod'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_linea_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf_linea_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='ventas_departamento_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_dep_complejo'),
        ),
        migrations.AddConstraint(
            model_name='ventas_departamento_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_dep_est'),
        ),
        migrations.AddConstraint(
            model_name='ventas_departamento_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_dep_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='ventas_linea_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_linea_complejo'),
        ),
        migrations.AddConstraint(
            model_name='ventas_linea_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_linea_prod'),
        ),
        migrations.AddConstraint(
            model_name='ventas_linea_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_linea_sucursal'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_sucursal',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_sucursal',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_sucursal',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_sucursal',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_sucursal',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_sucursal',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_establecimiento',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_establecimiento',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_establecimiento',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_establecimiento',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_establecimiento',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_establecimiento',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_complejo',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_complejo',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_complejo',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_complejo',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_complejo',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='ventas_seccion_complejo',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_sucursal',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_sucursal',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_sucursal',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_sucursal',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_sucursal',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_sucursal',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_establecimiento',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_establecimiento',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_establecimiento',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_establecimiento',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_establecimiento',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_establecimiento',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_complejo',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_complejo',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_complejo',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_complejo',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_complejo',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='transferencia_seccion_complejo',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_sucursal',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_sucursal',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_sucursal',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_sucursal',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_sucursal',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_sucursal',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_establecimiento',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_establecimiento',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_establecimiento',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_establecimiento',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_establecimiento',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_establecimiento',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_complejo',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_complejo',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_complejo',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_complejo',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_complejo',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_complejo',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='compra_seccion_sucursal',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='compra_seccion_sucursal',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='compra_seccion_sucursal',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='compra_seccion_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_seccion_sucursal',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='compra_seccion_sucursal',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='compra_seccion_sucursal',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='compra_seccion_establecimiento',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='compra_seccion_establecimiento',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='compra_seccion_establecimiento',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='compra_seccion_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_seccion_establecimiento',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='compra_seccion_establecimiento',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='compra_seccion_establecimiento',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='compra_seccion_complejo',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='compra_seccion_complejo',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='compra_seccion_complejo',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='compra_seccion_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='compra_seccion_complejo',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='compra_seccion_complejo',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='compra_seccion_complejo',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_sucursal',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_sucursal',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_sucursal',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_sucursal',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_sucursal',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_sucursal',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_sucursal',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_establecimiento',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_establecimiento',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_establecimiento',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_establecimiento',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_establecimiento',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_establecimiento',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_establecimiento',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_complejo',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_actividad'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_complejo',
            name='area_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_complejo',
            name='est_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_establecimiento'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_complejo',
            name='familia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_familia'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_complejo',
            name='periodo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_periodo'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_complejo',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_proveedor'),
        ),
        migrations.AddField(
            model_name='ajuste_seccion_complejo',
            name='tipo_cod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipocodigo'),
        ),
        migrations.AddConstraint(
            model_name='ventas_seccion_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_seccion_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='ventas_seccion_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_seccion_prod'),
        ),
        migrations.AddConstraint(
            model_name='ventas_seccion_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='venta_seccion_complejo'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_seccion_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf_seccion_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_seccion_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf_seccion_prod'),
        ),
        migrations.AddConstraint(
            model_name='transferencia_seccion_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='transf_seccioncomplejo'),
        ),
        migrations.AddConstraint(
            model_name='inventario_seccion_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_seccion_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='inventario_seccion_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_seccion_prod'),
        ),
        migrations.AddConstraint(
            model_name='inventario_seccion_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='inv_seccion_complejo'),
        ),
        migrations.AddConstraint(
            model_name='compra_seccion_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_seccion_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='compra_seccion_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_seccion_prod'),
        ),
        migrations.AddConstraint(
            model_name='compra_seccion_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='compra_seccion_complejo'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_seccion_sucursal',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_seccion_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_seccion_establecimiento',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_seccion_prod'),
        ),
        migrations.AddConstraint(
            model_name='ajuste_seccion_complejo',
            constraint=models.UniqueConstraint(fields=('familia', 'est_id', 'prov_id', 'periodo_id', 'act_id', 'area_tipo', 'tipo_cod_id'), name='ajuste_seccion_complejo'),
        ),
    ]
