# Generated by Django 3.2.8 on 2022-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estad_minoristas', '0006_alter_n_familia_fam_id_oltp'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_OrigenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_prod_id_ods', models.IntegerField(unique=True)),
                ('origen_prod_descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
