# Generated by Django 3.2.8 on 2022-12-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estad_minoristas', '0008_auto_20221204_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_departamento_complejo',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_departamento_establecimiento',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_departamento_sucursal',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_linea_complejo',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_linea_establecimiento',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_linea_sucursal',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_producto_complejo',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_producto_sucursal',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_seccion_complejo',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_seccion_establecimiento',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventario_seccion_sucursal',
            name='area_tipo',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
