# Generated by Django 3.2.8 on 2022-12-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estad_minoristas', '0009_auto_20221207_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_departamento_complejo',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_departamento_establecimiento',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_departamento_sucursal',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_linea_complejo',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_linea_establecimiento',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_linea_sucursal',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_producto_complejo',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_producto_sucursal',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_complejo',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_establecimiento',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AddField(
            model_name='inventario_seccion_sucursal',
            name='area_tipo_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
        migrations.AlterField(
            model_name='ajuste_departamento_complejo',
            name='area_tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estad_minoristas.n_tipoarea'),
        ),
    ]
